---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
  roles:
    - role: weareinteractive.environment
      become: true
    - role: deploy
      become: true
